global:
  dequeue: true
  gc_interval: 5
  tx_idle_timeout: 5

rest_listener:
  use_gunicorn: false
  addr: ["127.0.0.1", 8000]
  # cert:
  # key:
    
endpoint:
- name: outbound-gw
  msa: true
  chain:
  - filter: exploder
    output_chain: msa-output
    msa: true
    max_attempts: 100
    rcpt_timeout: 40
    data_timeout: 70

- name: msa-output
  msa: true
  chain:
  - filter: router
    policy:
      name: dest_domain
  - filter: dkim
    key: dkim.key
    domain: sandbox.gloop.org
    selector: tachygraph20230720
  - filter: rest_output
    static_endpoint: http://localhost:8001
    http_host: outbound
    remote_host_discovery: mx
    rcpt_timeout: 30
    data_timeout: 60

- name: inbound-gw
  msa: false
  chain:
  - filter: exploder
    msa: False
    output_chain: mx-out
    max_attempts: 3
    rcpt_timeout: 40
    data_timeout: 70

- name: mx-out
  msa: false
  chain:
  - filter: router
    policy:
      name: local_domain
      domains:
      - name: sandbox.gloop.org
  - filter: rest_output
    static_endpoint: http://localhost:8001
    http_host: outbound
    static_remote_host:
      host: aspmx.l.google.com
      port: 25
    rcpt_timeout: 30
    data_timeout: 60


storage:
  db_filename: storage.sqlite3


