Delivered-To: xyz@gmail.com
Received: by 2002:a05:6359:4592:b0:17b:16d2:be66 with SMTP id no18csp970624rwb;
        Thu, 15 Feb 2024 11:48:30 -0800 (PST)
Return-Path: <>
Received: from mail-sor-f69.google.com (mail-sor-f69.google.com. [209.85.220.69])
        by mx.google.com with SMTPS id u21-20020a056870441500b0021a8fbaae34sor638591oah.3.2024.02.15.11.48.30
        for <xyz@gmail.com>
        (Google Transport Security);
        Thu, 15 Feb 2024 11:48:30 -0800 (PST)
Received-SPF: none (google.com: mail-sor-f69.google.com does not designate permitted sender hosts) client-ip=209.85.220.69;
Content-Type: multipart/report; boundary="00000000000068645e061170e970"; report-type=delivery-status
To: xyz@gmail.com
Received: by 2002:a05:6870:8e17:b0:219:fddc:1edf with SMTP id
 lw23-20020a0568708e1700b00219fddc1edfmr3052869oab.8; Thu, 15 Feb 2024
 11:48:30 -0800 (PST)
Return-Path: <>
Auto-Submitted: auto-replied
Message-ID: <65ce6a8e.050a0220.6082e.8b75.GMR@mx.google.com>
Date: Thu, 15 Feb 2024 11:48:30 -0800 (PST)
From: Mail Delivery Subsystem <mailer-daemon@googlemail.com>
Subject: Delivery Status Notification (Failure)
References: <CAPd40h3zsBMTMCjqvczrAWqDJo=agZ39tc9Fn=FpwDhjTQMTVw@mail.gmail.com>
In-Reply-To: <CAPd40h3zsBMTMCjqvczrAWqDJo=agZ39tc9Fn=FpwDhjTQMTVw@mail.gmail.com>
X-Failed-Recipients: xyz@sandbox.gloop.org

--00000000000068645e061170e970
Content-Type: multipart/related; boundary="0000000000006878af061170e9a0"

--0000000000006878af061170e9a0
Content-Type: multipart/alternative; boundary="0000000000006878b5061170e9a1"

--0000000000006878b5061170e9a1
Content-Type: text/plain; charset="UTF-8"


** Message blocked **

Your message to xyz@sandbox.gloop.org has been blocked. See technical details below for more information.

Learn more here: https://support.google.com/mail/answer/69585

The response was:

Message rejected. For more information, go to https://support.google.com/mail/answer/69585

--0000000000006878b5061170e9a1
Content-Type: text/html; charset="UTF-8"


<html>
<head>
</head>
<body>
Your message to <a style='color:#212121;text-decoration:none'><b>xyz@sandbox.gloop.org</b></a> has been blocked. See technical details below for more information.
</body>
</html>

--0000000000006878b5061170e9a1--
--0000000000006878af061170e9a0
Content-Type: image/png; name="icon.png"
Content-Disposition: attachment; filename="icon.png"
Content-Transfer-Encoding: base64
Content-ID: <icon.png>

iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAAAXNSR0IArs4c6QAAAAlwSFlzAAAW
--0000000000006878af061170e9a0--
--00000000000068645e061170e970
Content-Type: message/delivery-status

Reporting-MTA: dns; googlemail.com
Arrival-Date: Thu, 15 Feb 2024 11:48:29 -0800 (PST)
X-Original-Message-ID: <CAPd40h3zsBMTMCjqvczrAWqDJo=agZ39tc9Fn=FpwDhjTQMTVw@mail.gmail.com>

Final-Recipient: rfc822; xyz@sandbox.gloop.org
Action: failed
Status: 4.4.2
Diagnostic-Code: smtp; Message rejected. For more information, go to https://support.google.com/mail/answer/69585
Last-Attempt-Date: Thu, 15 Feb 2024 11:48:30 -0800 (PST)

--00000000000068645e061170e970
Content-Type: message/rfc822

MIME-Version: 1.0
From: John Bucy <xyz@gmail.com>
Date: Thu, 15 Feb 2024 11:48:18 -0800
Message-ID: <CAPd40h3zsBMTMCjqvczrAWqDJo=agZ39tc9Fn=FpwDhjTQMTVw@mail.gmail.com>
Subject: 2/15 #2
To: John Bucy <xyz@sandbox.gloop.org>
Content-Type: multipart/alternative; boundary="000000000000639ae6061170e934"

--000000000000639ae6061170e934
Content-Type: text/plain; charset="UTF-8"



--000000000000639ae6061170e934
Content-Type: text/html; charset="UTF-8"

<div dir="ltr"><br></div>

--000000000000639ae6061170e934--

--00000000000068645e061170e970--
